#!/usr/bin/env python3
"""
Comprehensive audit of SROGs and PODs profiles against the spec.
"""

# SROGS SPEC (from Discovery Doc Profiles.md)
SROGS_SPEC = {
    "SROGsGeneral": 56,
    "IsOwner": 22,
    "IsManager": 20,
    "HasVermin": 13,
    "HasInsects": 13,
    "HasAnts": 13,
    "HasRoaches": 13,
    "HasFlies": 13,
    "HasBedbugs": 13,
    "HasBees": 13,
    "HasWasps": 13,
    "HasHornets": 13,
    "HasSpiders": 13,
    "HasTermites": 13,
    "HasMosquitos": 13,
    "HasHeater": 7,
    "HasAC": 7,
    "HasVentilation": 7,
    "HasOutlets": 7,
    "HasPanel": 7,
    "HasWallSwitches": 7,
    "HasExteriorLighting": 7,
    "HasInteriorLighting": 7,
    "HasLightFixtures": 7,
    "HasFans": 7,
    "HasSmokeAlarms": 7,
    "HasFireExtinguisher": 4,
    "HasNoncompliantElectricity": 7,
    "HasNonGfiElectricalOutlets": 7,
    "HasCarbonmonoxideDetectors": 7,
    "HasGovContact": 7,
    "HasStove": 7,
    "HasDishwasher": 7,
    "HasWasherDryer": 7,
    "HasOven": 7,
    "HasMicrowave": 7,
    "HasGarbageDisposal": 7,
    "HasRefrigerator": 7,
    "HasToilet": 7,
    "HasShower": 7,
    "HasBath": 7,
    "HasFixtures": 7,
    "HasLeaks": 7,
    "HasInsufficientWaterPressure": 7,
    "HasNoHotWater": 7,
    "HasSewageComingOut": 7,
    "HasCloggedToilet": 7,
    "HasCloggedBath": 7,
    "HasCloggedSink": 7,
    "HasCloggedShower": 7,
    "HasCabinets": 7,
    "HasCabinetsBroken": 7,
    "HasCabinetHinges": 7,
    "HasCabinetAlignment": 7,
    "HasUnevenFlooring": 7,
    "HasCarpet": 7,
    "HasTiles": 7,
    "HasNailsStickingOut": 7,
    "HasBrokenWindows": 7,
    "HasWindowScreens": 7,
    "HasWindowLeaks": 7,
    "HasWindowsDoNotLock": 7,
    "HasBrokenDoors": 17,
    "HasDoorKnobs": 7,
    "HasDoorLocks": 7,
    "HasBrokenHinges": 7,
    "HasSlidingGlassDoors": 7,
    "HasIneffectiveWaterproofing": 7,
    "HasWaterIntrusionInsects": 7,
    "HasBumpsInCeiling": 7,
    "HasHoleInCeiling": 7,
    "HasWaterStainsOnCeiling": 7,
    "HasWaterStainsOnWall": 7,
    "HasHoleInWall": 7,
    "HasPaint": 8,
    "HasExteriorDeckPorch": 7,
    "HasWaterproofToilet": 7,
    "HasWaterproofTub": 7,
    "HasStaircase": 7,
    "HasBasementFlood": 7,
    "HasLeaksInGarage": 20,
    "HasMailboxBroken": 7,
    "HasParkingAreaIssues": 7,
    "HasDamageToCars": 7,
    "HasFlooding": 7,
    "HasEntrancesBlocked": 7,
    "HasSwimmingPool": 7,
    "HasJacuzzi": 7,
    "HasElevator": 18,
    "HasLaundryRoom": 7,
    "HasRecreationRoom": 7,
    "HasGym": 7,
    "HasBlockedAreasDoors": 7,
    "HasTrashProblems": 6,
    "HasInadequateNumberOfTrashReceptacles": 6,
    "HasInadequateServicingAndEmptyingTrashReceptacles": 6,
    "HasDrugs": 6,
    "HasSmoking": 6,
    "HasNoisyNeighbors": 6,
    "HasGangs": 7,
    "HasMold": 24,
    "HasMildew": 15,
    "HasMushrooms": 15,
    "HasRawSewageOnExterior": 15,
    "HasNoxiousFumes": 15,
    "HasChemicalsPaintContamination": 15,
    "HasUnlawfulDetainer": 7,
    "HasEvictionThreat": 6,
    "HasHarrassmentByDefendants": 6,
    "HasHarrassmentMaintenanceManWorkers": 6,
    "HasHarrassmentManagerStaff": 6,
    "HasHarrassmentByOwnerAndTheirGuests": 6,
    "HasHarrassmentOtherTenants": 6,
    "HasIllegitimateNotices": 6,
    "HasRefusalToMakeTimelyRepairs": 6,
    "HasWrittenThreats": 6,
    "HasAggressiveInappropriateLanguage": 6,
    "HasPhysicalThreatsOrTouching": 6,
    "HasNoticesSinglingOutOneTenant": 6,
    "HasDuplicativeNotices": 6,
    "HasNotices": 14,
    "HasGasLeaks": 9,
    "HasWaterShutoffs": 9,
    "HasElectricityShutoffs": 9,
    "HasInjury": 8,
    "HasNonresponsiveLandlord": 6,
    "HasUnauthorizedEntries": 9,
    "HasStolenItems": 7,
    "HasDamagedItems": 6,
    "HasSafety": 20,
    "HasBrokenSecurityGate": 10,
    "HasInoperableLocks": 10,
    "HasSecurityCameras": 14,
    "HasAgeDiscrimination": 21,
    "HasDisabilityDiscrimination": 20,
    "HasRacialDiscrimination": 19,
    "HasSecurityDeposit": 20,
}

# SROGS CODE (from srogs_complete.py)
SROGS_CODE = {
    "SROGsGeneral": 56,
    "IsOwner": 22,
    "IsManager": 20,
    "HasInsects": 13,
    "HasAnts": 12,
    "HasRoaches": 13,
    "HasFlies": 10,
    "HasBedbugs": 13,
    "HasBees": 4,
    "HasWasps": 6,
    "HasHornets": 5,
    "HasSpiders": 8,
    "HasTermites": 7,
    "HasMosquitos": 3,
    "HasRatsMice": 18,
    "HasSkunks": 6,
    "HasBats": 5,
    "HasRaccoons": 7,  # Note: Raccoons vs Racoons
    "HasPigeons": 4,
    "HasOpossums": 3,
    "HasVermin": 20,
    "HasHeater": 7,
    "HasAC": 7,
    "HasVentilation": 6,
    "HasHVAC": 8,  # Note: HVAC vs Hvac
    "HasOutlets": 8,
    "HasPanel": 6,
    "HasWallSwitches": 5,
    "HasExteriorLighting": 4,
    "HasInteriorLighting": 6,
    "HasLightFixtures": 5,
    "HasFans": 3,
    "HasElectricalIssues": 10,  # Note: different name
    "HasToilet": 6,
    "HasShower": 6,
    "HasBath": 4,
    "HasFixtures": 5,
    "HasLeaks": 12,
    "HasInsufficientWaterPressure": 8,
    "HasNoHotWater": 10,
    "HasSewageComingOut": 15,
    "HasCloggedToilet": 8,
    "HasCloggedBath": 6,
    "HasCloggedSink": 7,
    "HasCloggedShower": 6,
    "HasNoCleanWaterSupply": 12,
    "HasNoColdWater": 8,
    "HasUnsanitaryWater": 14,
    "HasClogs": 9,
    "HasPlumbingIssues": 12,  # Note: different name
    "HasSmokeAlarms": 8,
    "HasFireExtinguisher": 6,
    "HasNonCompliantElectricity": 10,
    "HasNonGfiElectricalOutlets": 8,
    "HasCarbonmonoxideDetectors": 7,
    "HasFireHazardIssues": 12,  # Note: different name
    "HasDepartmentOfEnvironmentalHealth": 8,
    "HasDepartmentOfPublicHealth": 6,
    "HasDepartmentOfHealthServices": 5,
    "HasFireDepartment": 4,
    "HasPoliceDepartment": 6,
    "HasCodeEn": 7,  # Note: truncated name
    "HasGovContact": 10,
    "HasStove": 6,
    "HasDishwasher": 5,
    "HasWasherDryer": 7,
    "HasOven": 4,
    "HasMicrowave": 4,
    "HasGarbageDisposal": 3,
    "HasRefrigerator": 6,
    "HasAppliances": 8,
    "HasCabinets": 3,
    "HasCabinetsBroken": 5,
    "HasCabinetHinges": 4,
    "HasCabinetAlignment": 3,
    "HasUnevenFlooring": 6,
    "HasCarpet": 4,
    "HasTiles": 3,
    "HasNailsStickingOut": 7,
    "HasFlooringIssues": 8,  # Note: different name
    "HasBrokenWindows": 10,
    "HasWindowScreens": 4,
    "HasWindowLeaks": 8,
    "HasWindowsDoNotLock": 6,
    "HasMissingWindows": 7,
    "HasBrokenMissingScreens": 5,
    "HasWindowsIssues": 9,  # Note: different name
    "HasBrokenDoors": 17,
    "HasDoorKnobs": 4,
    "HasDoorLocks": 6,
    "HasBrokenHinges": 5,
    "HasSlidingGlassDoors": 4,
    "HasIneffectiveWaterproofing": 6,
    "HasWaterIntrusionInsects": 8,
    "HasDoorsDoNotCloseProperly": 7,
    "HasDoorIssues": 10,  # Note: different name
    "HasHoleInCeiling": 8,
    "HasBumpsInCeiling": 5,
    "HasWaterStainsOnCeiling": 7,
    "HasWaterStainsOnWall": 6,
    "HasHoleInWall": 7,
    "HasPaint": 4,
    "HasExteriorDeckPorch": 5,
    "HasWaterproofToilet": 3,
    "HasWaterproofTub": 3,
    "HasStaircase": 4,
    "HasBasementFlood": 8,
    "HasLeaksInGarage": 6,
    "HasIneffectiveWeatherproofingOfAnyWindowsDoors": 9,
    "HasIneffectiveWaterproofingOfTheTubsToilet": 7,
    "HasSoftSpotsDueToLeaks": 8,
    "HasHolesInCeilingWalls": 9,
    "HasWaterStainsOnCeilingWalls": 8,
    "HasStructureIssues": 12,  # Note: different name
    "HasMailboxBroken": 3,
    "HasParkingAreaIssues": 4,
    "HasDamageToCars": 5,
    "HasFlooding": 8,
    "HasEntrancesBlocked": 6,
    "HasSwimmingPool": 3,
    "HasJacuzzi": 2,
    "HasLaundryRoom": 4,
    "HasRecreationRoom": 3,
    "HasGym": 2,
    "HasBlockedAreasDoors": 5,
    "HasElevator": 18,
    "HasFilthRubbishGarbage": 6,
    "HasCommonAreaVermin": 7,
    "HasBrokenGate": 4,
    "HasCommonAreaInsects": 5,
    "HasCommonAreasIssues": 10,  # Note: different name (Areas vs Area)
    "HasDrugs": 8,
    "HasSmoking": 6,
    "HasNoisyNeighbors": 7,
    "HasGangs": 9,
    "HasNuisanceIssues": 8,  # Note: different name
    "HasMold": 24,
    "HasMildew": 8,
    "HasMushrooms": 6,
    "HasRawSewageOnExterior": 12,
    "HasNoxiousFumes": 9,
    "HasChemicalsPaintContamination": 10,
    "HasToxicWaterPollution": 11,
    "HasOffensiveOdors": 7,
    "HasHealthHazardIssues": 15,  # Note: different name
    "HasUnlawfulDetainer": 12,
    "HasEvictionThreat": 10,
    "HasHarrassmentByDefendants": 14,
    "HasHarrassmentMaintenanceManWorkers": 12,
    "HasHarrassmentManagerStaff": 13,
    "HasHarrassmentByOwnerAndTheirGuests": 15,
    "HasHarrassmentOtherTenants": 11,
    "HasIllegitimateNotices": 9,
    "HasRefusalToMakeTimelyRepairs": 11,
    "HasWrittenThreats": 8,
    "HasAggressiveInappropriateLanguage": 9,
    "HasPhysicalThreatsOrTouching": 12,
    "HasNoticesSinglingOutOneTenant": 8,
    "HasDuplicativeNotices": 6,
    "HasUntimelyResponseFromLandlord": 7,
    "HasHarassmentIssues": 16,  # Note: different name
    "HasNotices": 8,
    "Has24HourNotices": 6,
    "Has3DayNotices": 7,
    "Has30DayNotices": 5,
    "Has60DayNotices": 4,
    "HasToQuitNotices": 6,
    "HasPerformOrQuit": 5,
    "HasWaterShutoffs": 8,
    "HasGasLeaks": 10,
    "HasElectricityShutoffs": 9,
    "HasHeatShutoffs": 7,
    "HasGasShutoffs": 6,
    "HasSafety": 6,
    "HasInoperableLocks": 14,
    "HasBrokenSecurityGate": 5,
    "HasSecurityCameras": 3,
    "HasBrokenBuzzerToGetIn": 4,
    "HasInjury": 8,
    "HasNonresponsiveLandlord": 7,
    "HasUnauthorizedEntries": 9,
    "HasStolenItems": 6,
    "HasDamagedItems": 5,
    "HasAgeDiscrimination": 8,
    "HasDisabilityDiscrimination": 9,
    "HasRacialDiscrimination": 10,
    "HasSecurityDeposit": 20,
    "HasTrashProblems": 6,
    "HasInadequateNumberOfTrashReceptacles": 4,
    "HasInadequateServicingAndEmptyingTrashReceptacles": 5,
    "HasLosAngeles": 1,
}

def audit_srogs():
    """Audit SROGs profile."""
    print("="*80)
    print("SROGS PROFILE AUDIT")
    print("="*80)

    # Check for naming mismatches
    print("\n🔍 NAMING ISSUES:")
    naming_issues = [
        ("HasElectricalIssues (code)", "spec doesn't have this - should match individual flags"),
        ("HasPlumbingIssues (code)", "spec doesn't have this - should match individual flags"),
        ("HasFireHazardIssues (code)", "spec doesn't have this - should match individual flags"),
        ("HasFlooringIssues (code)", "spec doesn't have this - should match individual flags"),
        ("HasWindowsIssues (code)", "spec doesn't have this - should match individual flags"),
        ("HasDoorIssues (code)", "spec doesn't have this - should match individual flags"),
        ("HasStructureIssues (code)", "spec doesn't have this - should match individual flags"),
        ("HasCommonAreasIssues (code)", "spec doesn't have this - should match individual flags"),
        ("HasNuisanceIssues (code)", "spec doesn't have this - should match individual flags"),
        ("HasHealthHazardIssues (code)", "spec doesn't have this - should match individual flags"),
        ("HasHarassmentIssues (code)", "spec doesn't have this - should match individual flags"),
        ("HasRaccoons (code)", "spec has HasRacoons"),
        ("HasHVAC (code)", "spec has individual HVAC flags only"),
        ("HasCodeEn (code)", "appears truncated - should be HasCodeEnforcement?"),
    ]

    for issue, note in naming_issues:
        print(f"  ⚠️  {issue}: {note}")

    # Find count mismatches for matching flag names
    print("\n\n📊 COUNT DISCREPANCIES (for flags with matching names):")
    mismatches = []

    for flag in sorted(SROGS_SPEC.keys()):
        if flag in SROGS_CODE:
            spec_count = SROGS_SPEC[flag]
            code_count = SROGS_CODE[flag]
            if spec_count != code_count:
                diff = code_count - spec_count
                mismatches.append((flag, spec_count, code_count, diff))

    if mismatches:
        print(f"\nFound {len(mismatches)} count discrepancies:\n")
        print(f"{'Flag':<50} {'Spec':<10} {'Code':<10} {'Diff':<10}")
        print("-"*80)
        for flag, spec, code, diff in mismatches:
            symbol = "❌" if abs(diff) >= 3 else "⚠️"
            print(f"{symbol} {flag:<47} {spec:<10} {code:<10} {diff:+d}")

    print(f"\n{'='*80}\n")

# PODS SPEC (from Discovery Doc Profiles.md)
PODS_SPEC = {
    "IsOwner": 6,
    "IsManager": 1,
    "IsOwnerManager": 40,
    "HasVermin": 4,
    "HasRatsMice": 4,
    "HasSkunks": 4,
    "HasPigeons": 4,
    "HasBats": 4,
    "HasRacoons": 4,
    "HasOpossums": 4,
    "HasInsects": 4,
    "HasAnts": 4,
    "HasRoaches": 4,
    "HasFlies": 4,
    "HasBedbugs": 4,
    "HasBees": 4,
    "HasWasps": 4,
    "HasHornets": 4,
    "HasSpiders": 4,
    "HasTermites": 4,
    "HasMosquitos": 4,
    "HasAC": 5,
    "HasHeater": 5,
    "HasVentilation": 5,
    "HasOutlets": 5,
    "HasPanel": 5,
    "HasWallSwitches": 5,
    "HasExteriorLighting": 5,
    "HasInteriorLighting": 5,
    "HasLightFixtures": 5,
    "HasFans": 5,
    "HasSmokeAlarms": 5,
    "HasFireExtinguisher": 4,
    "HasNoncompliantElectricity": 5,
    "HasNonGfiElectricalOutlets": 4,
    "HasCarbonmonoxideDetectors": 5,
    "HasGovContact": 3,
    "HasDepartmentOfEnvironmentalHealth": 1,
    "HasDepartmentOfPublicHealth": 1,
    "HasDepartmentOfHealthServices": 1,
    "HasFireDepartment": 1,
    "HasPoliceDepartment": 1,
    "HasCodeEnforcement": 1,
    "HasStove": 5,
    "HasDishwasher": 5,
    "HasWasherDryer": 5,
    "HasOven": 5,
    "HasMicrowave": 5,
    "HasGarbageDisposal": 5,
    "HasRefrigerator": 5,
    "HasToilet": 5,
    "HasShower": 5,
    "HasBath": 5,
    "HasFixtures": 5,
    "HasLeaks": 4,
    "HasInsufficientWaterPressure": 4,
    "HasNoHotWater": 4,
    "HasSewageComingOut": 4,
    "HasClogs": 4,
    "HasCloggedToilet": 4,
    "HasCloggedBath": 4,
    "HasCloggedSink": 4,
    "HasCloggedShower": 4,
    "HasCabinets": 5,
    "HasCabinetsBroken": 5,
    "HasCabinetHinges": 5,
    "HasCabinetAlignment": 5,
    "HasUnevenFlooring": 5,
    "HasCarpet": 5,
    "HasTiles": 5,
    "HasNailsStickingOut": 4,
    "HasBrokenWindows": 5,
    "HasWindowScreens": 5,
    "HasWindowLeaks": 5,
    "HasWindowsDoNotLock": 5,
    "HasBrokenDoors": 10,
    "HasDoorKnobs": 5,
    "HasDoorLocks": 5,
    "HasBrokenHinges": 5,
    "HasSlidingGlassDoors": 5,
    "HasIneffectiveWaterproofing": 5,
    "HasWaterIntrusionInsects": 5,
    "HasBumpsInCeiling": 4,
    "HasHoleInCeiling": 4,
    "HasWaterStainsOnCeiling": 4,
    "HasWaterStainsOnWall": 4,
    "HasHoleInWall": 4,
    "HasPaint": 4,
    "HasExteriorDeckPorch": 4,
    "HasWaterproofToilet": 4,
    "HasWaterproofTub": 4,
    "HasStaircase": 4,
    "HasBasementFlood": 4,
    "HasLeaksInGarage": 9,
    "HasMailboxBroken": 5,
    "HasParkingAreaIssues": 5,
    "HasDamageToCars": 5,
    "HasFlooding": 4,
    "HasEntrancesBlocked": 5,
    "HasSwimmingPool": 4,
    "HasJacuzzi": 4,
    "HasElevator": 4,
    "HasLaundryRoom": 4,
    "HasRecreationRoom": 4,
    "HasGym": 4,
    "HasBlockedAreasDoors": 4,
    "HasTrashProblems": 5,
    "HasInadequateNumberOfTrashReceptacles": 5,
    "HasInadequateServicingAndEmptyingTrashReceptacles": 5,
    "HasDrugs": 4,
    "HasSmoking": 4,
    "HasNoisyNeighbors": 4,
    "HasGangs": 4,
    "HasMold": 4,
    "HasMildew": 4,
    "HasMushrooms": 4,
    "HasRawSewageOnExterior": 4,
    "HasNoxiousFumes": 4,
    "HasChemicalsPaintContamination": 4,
    "HasUnlawfulDetainer": 2,
    "HasEvictionThreat": 3,
    "HasHarrassmentByDefendants": 3,
    "HasHarrassmentMaintenanceManWorkers": 5,
    "HasHarrassmentManagerStaff": 5,
    "HasHarrassmentByOwnerAndTheirGuests": 5,
    "HasHarrassmentOtherTenants": 5,
    "HasIllegitimateNotices": 5,
    "HasRefusalToMakeTimelyRepairs": 5,
    "HasWrittenThreats": 5,
    "HasAggressiveInappropriateLanguage": 5,
    "HasPhysicalThreatsOrTouching": 5,
    "HasNoticesSinglingOutOneTenant": 5,
    "HasDuplicativeNotices": 5,
    "HasNotices": 1,
    "Has24HourNotices": 1,
    "Has3DayNotices": 1,
    "Has30DayNotices": 1,
    "Has60DayNotices": 1,
    "HasToQuitNotices": 1,
    "HasGasLeaks": 5,
    "HasWaterShutoffs": 5,
    "HasElectricityShutoffs": 5,
    "HasInjury": 4,
    "HasNonresponsiveLandlord": 5,
    "HasUnauthorizedEntries": 10,
    "HasStolenItems": 5,
    "HasDamagedItems": 5,
    "HasBrokenSecurityGate": 5,
    "HasBrokenBuzzerToGetIn": 5,
    "HasSecurityCameras": 5,
    "HasInoperableLocks": 5,
    "HasAgeDiscrimination": 21,
    "HasDisabilityDiscrimination": 20,
    "HasRacialDiscrimination": 19,
    "HasSecurityDeposit": 22,
}

# PODS CODE (from pods_complete.py)
PODS_CODE = {
    "IsOwner": 6,
    "IsManager": 1,
    "IsOwnerManager": 40,
    "HasInsects": 4,
    "HasAnts": 3,
    "HasRoaches": 4,
    "HasFlies": 2,
    "HasBedbugs": 4,
    "HasBees": 1,
    "HasWasps": 1,
    "HasHornets": 1,
    "HasSpiders": 2,
    "HasTermites": 2,
    "HasMosquitos": 1,
    "HasRatsMice": 6,
    "HasSkunks": 2,
    "HasBats": 1,
    "HasRacoons": 2,
    "HasPigeons": 1,
    "HasOpossums": 1,
    "HasVermin": 8,
    "HasHeater": 5,
    "HasAC": 5,
    "HasVentilation": 3,
    "HasHvac": 6,
    "HasOutlets": 2,
    "HasPanel": 1,
    "HasWallSwitches": 1,
    "HasExteriorLighting": 1,
    "HasInteriorLighting": 2,
    "HasLightFixtures": 1,
    "HasFans": 1,
    "HasElectrical": 3,
    "HasToilet": 1,
    "HasShower": 1,
    "HasBath": 1,
    "HasFixtures": 1,
    "HasLeaks": 2,
    "HasInsufficientWaterPressure": 1,
    "HasNoHotWater": 2,
    "HasSewageComingOut": 3,
    "HasCloggedToilet": 1,
    "HasCloggedBath": 1,
    "HasCloggedSink": 1,
    "HasCloggedShower": 1,
    "HasNoCleanWaterSupply": 2,
    "HasNoColdWater": 1,
    "HasUnsanitaryWater": 2,
    "HasClogs": 2,
    "HasPlumbing": 3,
    "HasSmokeAlarms": 1,
    "HasFireExtinguisher": 1,
    "HasNonCompliantElectricity": 2,
    "HasNonGfiElectricalOutlets": 1,
    "HasCarbonmonoxideDetectors": 1,
    "HasFireHazard": 3,
    "HasDepartmentOfEnvironmentalHealth": 1,
    "HasDepartmentOfPublicHealth": 1,
    "HasDepartmentOfHealthServices": 1,
    "HasFireDepartment": 1,
    "HasPoliceDepartment": 1,
    "HasCodeEnforcement": 1,
    "HasGovContact": 2,
    "HasStove": 1,
    "HasDishwasher": 1,
    "HasWasherDryer": 2,
    "HasOven": 1,
    "HasMicrowave": 1,
    "HasGarbageDisposal": 1,
    "HasRefrigerator": 1,
    "HasAppliances": 2,
    "HasCabinets": 1,
    "HasCabinetsBroken": 1,
    "HasCabinetHinges": 1,
    "HasCabinetAlignment": 1,
    "HasUnevenFlooring": 1,
    "HasCarpet": 1,
    "HasTiles": 1,
    "HasNailsStickingOut": 1,
    "HasFloors": 2,
    "HasBrokenWindows": 2,
    "HasWindowScreens": 1,
    "HasWindowLeaks": 1,
    "HasWindowsDoNotLock": 1,
    "HasMissingWindows": 1,
    "HasBrokenMissingScreens": 1,
    "HasWindows": 2,
    "HasBrokenDoors": 10,
    "HasDoorKnobs": 1,
    "HasDoorLocks": 1,
    "HasBrokenHinges": 1,
    "HasSlidingGlassDoors": 1,
    "HasIneffectiveWaterproofing": 1,
    "HasWaterIntrusionInsects": 1,
    "HasDoorsDoNotCloseProperly": 1,
    "HasDoors": 3,
    "HasHoleInCeiling": 1,
    "HasBumpsInCeiling": 1,
    "HasWaterStainsOnCeiling": 1,
    "HasWaterStainsOnWall": 1,
    "HasHoleInWall": 1,
    "HasPaint": 1,
    "HasExteriorDeckPorch": 1,
    "HasWaterproofToilet": 1,
    "HasWaterproofTub": 1,
    "HasStaircase": 1,
    "HasBasementFlood": 1,
    "HasLeaksInGarage": 1,
    "HasIneffectiveWeatherproofingOfAnyWindowsDoors": 1,
    "HasIneffectiveWaterproofingOfTheTubsToilet": 1,
    "HasSoftSpotsDueToLeaks": 1,
    "HasHolesInCeilingWalls": 1,
    "HasWaterStainsOnCeilingWalls": 1,
    "HasStructure": 2,
    "HasMailboxBroken": 1,
    "HasParkingAreaIssues": 1,
    "HasDamageToCars": 1,
    "HasFlooding": 1,
    "HasEntrancesBlocked": 1,
    "HasSwimmingPool": 1,
    "HasJacuzzi": 1,
    "HasLaundryRoom": 1,
    "HasRecreationRoom": 1,
    "HasGym": 1,
    "HasBlockedAreasDoors": 1,
    "HasElevator": 4,
    "HasFilthRubbishGarbage": 1,
    "HasCommonAreaVermin": 1,
    "HasBrokenGate": 1,
    "HasCommonAreaInsects": 1,
    "HasCommonArea": 2,
    "HasDrugs": 1,
    "HasSmoking": 1,
    "HasNoisyNeighbors": 1,
    "HasGangs": 1,
    "HasNuisance": 2,
    "HasMold": 4,
    "HasMildew": 1,
    "HasMushrooms": 1,
    "HasRawSewageOnExterior": 1,
    "HasNoxiousFumes": 1,
    "HasChemicalsPaintContamination": 1,
    "HasToxicWaterPollution": 1,
    "HasOffensiveOdors": 1,
    "HasHealthHazards": 2,
    "HasUnlawfulDetainer": 1,
    "HasEvictionThreat": 1,
    "HasHarrassmentByDefendants": 1,
    "HasHarrassmentMaintenanceManWorkers": 1,
    "HasHarrassmentManagerStaff": 1,
    "HasHarrassmentByOwnerAndTheirGuests": 1,
    "HasHarrassmentOtherTenants": 1,
    "HasIllegitimateNotices": 1,
    "HasRefusalToMakeTimelyRepairs": 1,
    "HasWrittenThreats": 1,
    "HasAggressiveInappropriateLanguage": 1,
    "HasPhysicalThreatsOrTouching": 1,
    "HasNoticesSinglingOutOneTenant": 1,
    "HasDuplicativeNotices": 1,
    "HasUntimelyResponseFromLandlord": 1,
    "HasHarassment": 2,
    "HasNotices": 1,
    "Has24HourNotices": 1,
    "Has3DayNotices": 1,
    "Has30DayNotices": 1,
    "Has60DayNotices": 1,
    "HasToQuitNotices": 1,
    "HasPerformOrQuit": 1,
    "HasWaterShutoffs": 1,
    "HasGasLeaks": 1,
    "HasElectricityShutoffs": 1,
    "HasHeatShutoffs": 1,
    "HasGasShutoffs": 1,
    "HasSafety": 1,
    "HasInoperableLocks": 1,
    "HasBrokenSecurityGate": 1,
    "HasSecurityCameras": 1,
    "HasBrokenBuzzerToGetIn": 1,
    "HasInjury": 1,
    "HasNonresponsiveLandlord": 1,
    "HasUnauthorizedEntries": 1,
    "HasStolenItems": 1,
    "HasDamagedItems": 1,
    "HasAgeDiscrimination": 1,
    "HasDisabilityDiscrimination": 1,
    "HasRacialDiscrimination": 1,
    "HasSecurityDeposit": 22,
    "HasTrashProblems": 1,
    "HasInadequateNumberOfTrashReceptacles": 1,
    "HasInadequateServicingAndEmptyingTrashReceptacles": 1,
    "HasLosAngeles": 1,
}

def audit_pods():
    """Audit PODs profile."""
    print("="*80)
    print("PODS PROFILE AUDIT")
    print("="*80)

    # Find count mismatches
    print("\n📊 COUNT DISCREPANCIES:")
    mismatches = []

    for flag in sorted(PODS_SPEC.keys()):
        spec_count = PODS_SPEC[flag]
        code_count = PODS_CODE.get(flag, "MISSING")

        if code_count == "MISSING":
            mismatches.append((flag, spec_count, "MISSING", f"-{spec_count}"))
        elif spec_count != code_count:
            diff = code_count - spec_count
            mismatches.append((flag, spec_count, code_count, f"{diff:+d}"))

    if mismatches:
        print(f"\nFound {len(mismatches)} discrepancies:\n")
        print(f"{'Flag':<50} {'Spec':<10} {'Code':<10} {'Diff':<10}")
        print("-"*80)
        for flag, spec, code, diff in mismatches:
            symbol = "❌" if (isinstance(code, int) and abs(code - spec) >= 3) or code == "MISSING" else "⚠️"
            print(f"{symbol} {flag:<47} {spec:<10} {str(code):<10} {diff:<10}")

    print(f"\n{'='*80}\n")

if __name__ == "__main__":
    audit_srogs()
    audit_pods()
