/**
 * Client Intake Routes
 *
 * Handles client intake form submissions and stores them in the database.
 * Maps form data to the client_intakes table schema.
 */

const express = require('express');
const router = express.Router();
const logger = require('../monitoring/logger');
const { getDb } = require('../services/database-service');

/**
 * POST /api/intakes
 * Submit a new client intake form
 */
router.post('/', async (req, res) => {
  const startTime = Date.now();

  try {
    const formData = req.body;
    logger.info('Received intake form submission', {
      firstName: formData.firstName,
      lastName: formData.lastName,
      email: formData.emailAddress,
    });

    // Validate required fields
    const requiredFields = [
      'firstName',
      'lastName',
      'primaryPhone',
      'emailAddress',
      'currentStreetAddress',
      'currentCity',
      'currentState',
      'currentZipCode',
      'propertyStreetAddress',
      'propertyCity',
      'propertyState',
      'propertyZipCode',
      'monthlyRent',
      'primaryIssue',
      'issueDescription',
    ];

    const missingFields = requiredFields.filter(field => !formData[field]);
    if (missingFields.length > 0) {
      logger.warn('Missing required fields in intake submission', {
        missingFields,
      });
      return res.status(400).json({
        error: 'Missing required fields',
        missingFields,
      });
    }

    const db = getDb();

    // Insert into client_intakes table
    // The intake_number will be auto-generated by the database trigger
    const query = `
      INSERT INTO client_intakes (
        first_name,
        middle_name,
        last_name,
        date_of_birth,
        primary_phone,
        email_address,
        current_street_address,
        current_city,
        current_state,
        current_zip_code,
        property_street_address,
        property_city,
        property_state,
        property_zip_code,
        monthly_rent,
        lease_start_date,
        primary_issue_category,
        issue_description,
        intake_status,
        submitted_by_ip,
        raw_form_data
      ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21
      )
      RETURNING id, intake_number, intake_date, intake_status
    `;

    const values = [
      formData.firstName,
      formData.middleName || null,
      formData.lastName,
      formData.dateOfBirth || null,
      formData.primaryPhone,
      formData.emailAddress,
      formData.currentStreetAddress,
      formData.currentCity,
      formData.currentState,
      formData.currentZipCode,
      formData.propertyStreetAddress,
      formData.propertyCity,
      formData.propertyState,
      formData.propertyZipCode,
      parseFloat(formData.monthlyRent),
      formData.leaseStartDate || null,
      formData.primaryIssue,
      formData.issueDescription,
      'pending', // Default status
      req.ip || req.connection.remoteAddress,
      JSON.stringify(formData), // Store raw form data for audit trail
    ];

    const result = await db.query(query, values);
    const intake = result.rows[0];

    const duration = Date.now() - startTime;
    logger.info('Intake form saved successfully', {
      intakeId: intake.id,
      intakeNumber: intake.intake_number,
      duration,
    });

    // Return success response with intake number
    res.status(201).json({
      success: true,
      intakeNumber: intake.intake_number,
      intakeId: intake.id,
      intakeDate: intake.intake_date,
      message: 'Your intake form has been submitted successfully. An attorney will review it shortly.',
    });

  } catch (error) {
    const duration = Date.now() - startTime;
    logger.error('Error saving intake form', {
      error: error.message,
      stack: error.stack,
      duration,
    });

    // Check for specific database errors
    if (error.code === '23505') { // Unique violation
      return res.status(409).json({
        error: 'Duplicate submission detected',
        message: 'This intake form may have already been submitted.',
      });
    }

    res.status(500).json({
      error: 'Internal server error',
      message: 'Failed to submit intake form. Please try again.',
    });
  }
});

/**
 * GET /api/intakes
 * List all intake submissions (for internal/admin use)
 */
router.get('/', async (req, res) => {
  try {
    const { status, limit = 50, offset = 0 } = req.query;

    const db = getDb();

    let query = `
      SELECT
        id,
        intake_number,
        intake_date,
        intake_status,
        first_name,
        last_name,
        email_address,
        primary_phone,
        property_city,
        property_state,
        primary_issue_category,
        created_at
      FROM client_intakes
    `;

    const values = [];
    let paramIndex = 1;

    // Filter by status if provided
    if (status) {
      query += ` WHERE intake_status = $${paramIndex}`;
      values.push(status);
      paramIndex++;
    }

    query += ` ORDER BY intake_date DESC LIMIT $${paramIndex} OFFSET $${paramIndex + 1}`;
    values.push(parseInt(limit), parseInt(offset));

    const result = await db.query(query, values);

    logger.info('Fetched intake list', {
      count: result.rows.length,
      status,
    });

    res.json({
      intakes: result.rows,
      count: result.rows.length,
      limit: parseInt(limit),
      offset: parseInt(offset),
    });

  } catch (error) {
    logger.error('Error fetching intakes', {
      error: error.message,
      stack: error.stack,
    });

    res.status(500).json({
      error: 'Internal server error',
      message: 'Failed to fetch intakes.',
    });
  }
});

/**
 * GET /api/intakes/:id
 * Get a specific intake by ID
 */
router.get('/:id', async (req, res) => {
  try {
    const { id } = req.params;

    const db = getDb();

    const query = `
      SELECT *
      FROM client_intakes
      WHERE id = $1
    `;

    const result = await db.query(query, [id]);

    if (result.rows.length === 0) {
      return res.status(404).json({
        error: 'Not found',
        message: 'Intake form not found.',
      });
    }

    logger.info('Fetched intake details', {
      intakeId: id,
      intakeNumber: result.rows[0].intake_number,
    });

    res.json({
      intake: result.rows[0],
    });

  } catch (error) {
    logger.error('Error fetching intake', {
      error: error.message,
      stack: error.stack,
      intakeId: req.params.id,
    });

    res.status(500).json({
      error: 'Internal server error',
      message: 'Failed to fetch intake.',
    });
  }
});

module.exports = router;
