/**
 * Issue Categories Configuration
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated: 2025-11-21T19:48:39.802Z
 * Source: Database (issue_categories, issue_options tables)
 *
 * This file is automatically generated from the database by:
 *   npm run generate:issue-config
 *
 * To add new categories or options:
 *   1. Add to database via migration
 *   2. Run: npm run generate:issue-config
 *   3. Commit the updated file
 *
 * @module shared/config/issue-categories-config
 */

/**
 * Issue Option Type
 */
export interface IssueOption {
    /** Unique option ID (UUID from database) */
    id: string;
    /** Option code (e.g., 'RatsMice', 'Bats') */
    code: string;
    /** Display name shown to users */
    name: string;
    /** Sort order within category */
    displayOrder: number;
}

/**
 * Issue Category Type
 */
export interface IssueCategory {
    /** Unique category ID (UUID from database) */
    id: string;
    /** Category code (e.g., 'vermin', 'insects') */
    code: string;
    /** Display name shown to users */
    name: string;
    /** Sort order in UI */
    displayOrder: number;
    /** Available options for this category */
    options: IssueOption[];
}

/**
 * All Issue Categories (from database)
 * 30 categories, 158 total options
 */
export const ISSUE_CATEGORIES: IssueCategory[] = [
    {
        id: '9af62347-656c-4cdc-9d55-987af4089eae',
        code: 'vermin',
        name: 'Vermin/Pests',
        displayOrder: 1,
        options: [
            {
                id: '9dfca6f4-1ded-438a-a50d-4061457e1e5f',
                code: 'RatsMice',
                name: 'Rats/Mice',
                displayOrder: 1
            },
            {
                id: 'e970b669-a984-42e7-a217-7362cb52260a',
                code: 'Skunks',
                name: 'Skunks',
                displayOrder: 2
            },
            {
                id: '42c625a7-d558-4679-86db-ae729449b1e2',
                code: 'Bats',
                name: 'Bats',
                displayOrder: 3
            },
            {
                id: 'bb03ef56-cc17-45cd-a9f5-625bd0cf550b',
                code: 'Raccoons',
                name: 'Raccoons',
                displayOrder: 4
            },
            {
                id: '890a771f-11c4-477f-84bd-88e8f1c4be66',
                code: 'Pigeons',
                name: 'Pigeons',
                displayOrder: 5
            },
            {
                id: 'dd099c03-d204-4760-902a-7c1a212bd98f',
                code: 'Opossums',
                name: 'Opossums',
                displayOrder: 6
            }
        ]
    },
    {
        id: '2de42aac-7501-4cdb-a6b9-1386bda00462',
        code: 'insects',
        name: 'Insect Infestation',
        displayOrder: 2,
        options: [
            {
                id: '5aaec412-d8df-4471-982e-6178e6ebbe2d',
                code: 'Ants',
                name: 'Ants',
                displayOrder: 1
            },
            {
                id: '3af36a72-c23d-4191-9926-dc39172f784f',
                code: 'Roaches',
                name: 'Roaches',
                displayOrder: 2
            },
            {
                id: 'a7b8f67c-8631-4713-be82-8bcced40df4b',
                code: 'Flies',
                name: 'Flies',
                displayOrder: 3
            },
            {
                id: '753205f6-3c80-4ef8-be2d-ebd040a3fe3f',
                code: 'Bedbugs',
                name: 'Bedbugs',
                displayOrder: 4
            },
            {
                id: 'e4091414-8a0e-478c-ba97-75e700789ec4',
                code: 'Wasps',
                name: 'Wasps',
                displayOrder: 5
            },
            {
                id: 'e004b1bd-3d20-4bd7-8b45-2e013c544bfa',
                code: 'Hornets',
                name: 'Hornets',
                displayOrder: 6
            },
            {
                id: '6a890fc1-f193-4bc6-9645-7203361f31b0',
                code: 'Spiders',
                name: 'Spiders',
                displayOrder: 7
            },
            {
                id: '06d8aa0f-df72-4ebb-9dae-723d824fedbe',
                code: 'Termites',
                name: 'Termites',
                displayOrder: 8
            },
            {
                id: '24c6d401-a372-44a9-b396-a26965380ba5',
                code: 'Mosquitos',
                name: 'Mosquitos',
                displayOrder: 9
            },
            {
                id: 'e47f8d46-bd83-404e-b045-a04ddf0f3a8e',
                code: 'Bees',
                name: 'Bees',
                displayOrder: 10
            }
        ]
    },
    {
        id: '0ec7a4cf-d3cc-4930-beeb-7103172861c6',
        code: 'hvac',
        name: 'HVAC Issues',
        displayOrder: 3,
        options: [
            {
                id: 'f755e9f4-44bb-4b3a-b114-bc5b87876780',
                code: 'AirConditioner',
                name: 'Air conditioner',
                displayOrder: 1
            },
            {
                id: '4c9e30d0-0079-4622-8d0c-422ac7c0f985',
                code: 'Heater',
                name: 'Heater',
                displayOrder: 2
            },
            {
                id: 'dd7028b9-868d-4020-b1ed-3cb8628fdc23',
                code: 'Ventilation',
                name: 'Ventilation',
                displayOrder: 3
            }
        ]
    },
    {
        id: '90a8b56b-faca-4fce-9e6c-22ce12d253f3',
        code: 'electrical',
        name: 'Electrical Problems',
        displayOrder: 4,
        options: [
            {
                id: '853ff26b-ec5d-4ebd-9020-c7912a58a2eb',
                code: 'Outlets',
                name: 'Outlets',
                displayOrder: 1
            },
            {
                id: 'baa99b45-862e-47e3-84fe-f556b2c55206',
                code: 'Panel',
                name: 'Panel',
                displayOrder: 2
            },
            {
                id: '18c75ed2-b5d5-441e-a5c9-561d940d7f87',
                code: 'WallSwitches',
                name: 'Wall switches',
                displayOrder: 3
            },
            {
                id: '64cfc298-1d1a-4db9-a9b9-6104b24627b0',
                code: 'ExteriorLighting',
                name: 'Exterior lighting',
                displayOrder: 4
            },
            {
                id: '29e318f3-8968-489e-8e68-d5ba1abc20b8',
                code: 'InteriorLighting',
                name: 'Interior lighting',
                displayOrder: 5
            },
            {
                id: '719e41c6-52a3-40b2-b72f-031111229c1d',
                code: 'LightFixtures',
                name: 'Light fixtures',
                displayOrder: 6
            },
            {
                id: '64fc1a6d-76e8-45e0-bbba-4ced72add2ce',
                code: 'Fans',
                name: 'Fans',
                displayOrder: 7
            }
        ]
    },
    {
        id: '76f8f998-e1f4-428b-b229-f5203cfbbfc2',
        code: 'fireHazard',
        name: 'Fire Hazards',
        displayOrder: 5,
        options: [
            {
                id: 'a109f0b2-5f85-431b-8e57-995fc1487fcd',
                code: 'SmokeAlarms',
                name: 'Smoke alarms',
                displayOrder: 1
            },
            {
                id: '7ebcedd2-cc53-4a0f-83f6-d42194c2f7ea',
                code: 'FireExtinguisher',
                name: 'Fire extinguisher',
                displayOrder: 2
            },
            {
                id: '73a89fd1-6f77-47d9-a3d2-634b6f826f81',
                code: 'Noncompliantelectricity',
                name: 'Non-compliant electricity',
                displayOrder: 3
            },
            {
                id: 'c795c129-e199-41ab-ad62-0637fe3acf71',
                code: 'NonGFIoutletsnearwater',
                name: 'Non-GFI outlets near water',
                displayOrder: 4
            },
            {
                id: '60034db4-a18b-464c-acb4-18999e1a1a79',
                code: 'Carbonmonoxidedetectors',
                name: 'Carbon monoxide detectors',
                displayOrder: 5
            }
        ]
    },
    {
        id: '843e790d-ed77-41be-bb0f-744270e92dcb',
        code: 'government',
        name: 'Government Contact',
        displayOrder: 6,
        options: [
            {
                id: '4398dc3d-b427-4d99-b8cc-9a0857ab99f0',
                code: 'HealthDepartment',
                name: 'Health department',
                displayOrder: 1
            },
            {
                id: '1e8c2ece-06a2-4661-8157-854685fa0d6d',
                code: 'HousingAuthority',
                name: 'Housing authority',
                displayOrder: 2
            },
            {
                id: 'a7a620c6-b66f-4b26-b888-d2d82e934b3e',
                code: 'CodeEnforcement',
                name: 'Code enforcement',
                displayOrder: 3
            },
            {
                id: '61748699-9571-45c1-a09a-3fef1f1e82c8',
                code: 'FireDepartment',
                name: 'Fire department',
                displayOrder: 4
            },
            {
                id: 'bcfb3204-29d7-4a5e-917c-e109a97b1068',
                code: 'PoliceDepartment',
                name: 'Police department',
                displayOrder: 5
            },
            {
                id: 'bef2ef08-c766-4a63-a291-db455afd1166',
                code: 'DepartmentofEnvironmentalHealth',
                name: 'Department of Environmental Health',
                displayOrder: 6
            },
            {
                id: '3157a1c2-763e-48d4-9493-266555ba022c',
                code: 'DepartmentofHealthServices',
                name: 'Department of health services',
                displayOrder: 7
            }
        ]
    },
    {
        id: '3b75ef28-1039-4009-b309-108d6c3a7796',
        code: 'appliances',
        name: 'Appliance Issues',
        displayOrder: 7,
        options: [
            {
                id: '01edc7fe-d09d-499a-a4f6-2a9f69d80674',
                code: 'Stove',
                name: 'Stove',
                displayOrder: 1
            },
            {
                id: '4b36855f-6817-4a09-be71-62acae4699c8',
                code: 'Dishwasher',
                name: 'Dishwasher',
                displayOrder: 2
            },
            {
                id: '86dcd3ae-14e7-4386-ae5a-734b53c18e63',
                code: 'Washerdryer',
                name: 'Washer/dryer',
                displayOrder: 3
            },
            {
                id: 'fda7c7b9-099e-4af0-b2bd-128a17692415',
                code: 'Oven',
                name: 'Oven',
                displayOrder: 4
            },
            {
                id: '4854dfd2-f3f6-41a8-b953-8ec9eb71f802',
                code: 'Microwave',
                name: 'Microwave',
                displayOrder: 5
            },
            {
                id: '4104d84b-9c85-4ec9-bf0d-6b26c6829571',
                code: 'Garbagedisposal',
                name: 'Garbage disposal',
                displayOrder: 6
            },
            {
                id: 'ca5a3842-0950-4320-8432-44513d64e8cc',
                code: 'Refrigerator',
                name: 'Refrigerator',
                displayOrder: 7
            }
        ]
    },
    {
        id: '52a9ff6f-97c0-4083-8178-01d2fa59e7c7',
        code: 'plumbing',
        name: 'Plumbing Problems',
        displayOrder: 8,
        options: [
            {
                id: '7232c91b-fc6c-4105-a47d-a8a6f58acb27',
                code: 'Toilet',
                name: 'Toilet',
                displayOrder: 1
            },
            {
                id: '3a1ea025-9072-4597-9273-4bd007ede271',
                code: 'Insufficientwaterpressure',
                name: 'Insufficient water pressure',
                displayOrder: 2
            },
            {
                id: 'e7151452-21b8-47b8-9221-9417dae3d297',
                code: 'Cloggedbath',
                name: 'Clogged bath',
                displayOrder: 3
            },
            {
                id: '71ef7287-14a9-4f68-a9a4-afedbeda8f36',
                code: 'Shower',
                name: 'Shower',
                displayOrder: 4
            },
            {
                id: '02ef77fd-8355-4141-b486-13a7ccc944e9',
                code: 'Nohotwater',
                name: 'No hot water',
                displayOrder: 5
            },
            {
                id: 'd2ad1e12-2ec1-4d30-ba86-8c2ccfb4bbd8',
                code: 'Cloggedsinks',
                name: 'Clogged sinks',
                displayOrder: 6
            },
            {
                id: '51f7dfbe-2f5c-47b5-a28e-7daa7aecd10f',
                code: 'Bath',
                name: 'Bath',
                displayOrder: 7
            },
            {
                id: 'c64470ab-1c0c-46b3-99e0-27abfe800ba7',
                code: 'Nocoldwater',
                name: 'No cold water',
                displayOrder: 8
            },
            {
                id: 'e53d3295-32d1-4241-a707-2a93eb0879c9',
                code: 'Cloggedshower',
                name: 'Clogged shower',
                displayOrder: 9
            },
            {
                id: '172c5a1a-c270-4e1b-a2cd-2bb295197659',
                code: 'Fixtures',
                name: 'Fixtures',
                displayOrder: 10
            },
            {
                id: '3a4e8c82-5eeb-4b36-a560-c7029aa7fb42',
                code: 'Sewagecomingout',
                name: 'Sewage coming out',
                displayOrder: 11
            },
            {
                id: '792dc526-89ba-478a-b9a3-c4676205a89a',
                code: 'NoCleanWaterSupply',
                name: 'No Clean Water Supply',
                displayOrder: 12
            },
            {
                id: 'bad14a42-4e37-40a4-8361-d26430483e58',
                code: 'Leaks',
                name: 'Leaks',
                displayOrder: 13
            },
            {
                id: '774d8d5b-0d19-466e-a653-c8f533e5a096',
                code: 'Cloggedtoilets',
                name: 'Clogged toilets',
                displayOrder: 14
            },
            {
                id: '0452c406-a15a-46bf-bb30-9c3568d203bb',
                code: 'Unsanitarywater',
                name: 'Unsanitary water',
                displayOrder: 15
            }
        ]
    },
    {
        id: 'b37d6a5f-4768-4355-a655-28dc4b951e90',
        code: 'cabinets',
        name: 'Cabinet Issues',
        displayOrder: 9,
        options: [
            {
                id: '39d4104c-7ef1-42f1-9ae6-3139de90ed3e',
                code: 'Broken',
                name: 'Broken',
                displayOrder: 1
            },
            {
                id: '437da732-8050-420c-98d3-a2bdd4fba648',
                code: 'Hinges',
                name: 'Hinges',
                displayOrder: 2
            },
            {
                id: '81ccb99d-ad81-40e9-8714-2b69532dfd41',
                code: 'Alignment',
                name: 'Alignment',
                displayOrder: 3
            }
        ]
    },
    {
        id: 'a43e83de-d8fd-4145-a9cc-9514a243913f',
        code: 'flooring',
        name: 'Flooring Problems',
        displayOrder: 10,
        options: [
            {
                id: 'aee24e32-888c-4260-ad6a-76d9a383a722',
                code: 'Uneven',
                name: 'Uneven',
                displayOrder: 1
            },
            {
                id: 'e5b9163a-6951-4a5d-ae0f-32dde3efaf29',
                code: 'Carpet',
                name: 'Carpet',
                displayOrder: 2
            },
            {
                id: 'd8a2ca9a-3b07-4e1c-b4be-228b1a160983',
                code: 'Nailsstickingout',
                name: 'Nails sticking out',
                displayOrder: 3
            },
            {
                id: 'b84d0274-f488-46db-9bd9-ab4938a2c232',
                code: 'Tiles',
                name: 'Tiles',
                displayOrder: 4
            }
        ]
    },
    {
        id: 'a648e350-56ca-472c-af26-dae7abe9d9ba',
        code: 'windows',
        name: 'Window Issues',
        displayOrder: 11,
        options: [
            {
                id: 'f08015ad-ce9b-4164-b5fb-8cfad3419d3b',
                code: 'Broken',
                name: 'Broken',
                displayOrder: 1
            },
            {
                id: 'de182517-1e8c-430d-ac2a-6a76882ee5e7',
                code: 'Screens',
                name: 'Screens',
                displayOrder: 2
            },
            {
                id: 'cc749c94-f08e-4762-ad16-9ecf3067e3f5',
                code: 'Leaks',
                name: 'Leaks',
                displayOrder: 3
            },
            {
                id: '60814370-ecfb-4c12-bd3c-755f2b3335e4',
                code: 'Donotlock',
                name: 'Do not lock',
                displayOrder: 4
            },
            {
                id: '89933950-abcd-4970-8f29-a6ab93ad7e99',
                code: 'Missingwindows',
                name: 'Missing windows',
                displayOrder: 5
            },
            {
                id: '022c102e-0269-4dbc-826c-e41b16a355a1',
                code: 'Brokenormissingscreens',
                name: 'Broken or missing screens',
                displayOrder: 6
            }
        ]
    },
    {
        id: 'db9a9be2-01af-478f-979a-53eeaf68390a',
        code: 'doors',
        name: 'Door Problems',
        displayOrder: 12,
        options: [
            {
                id: 'd4f6ed02-9964-4fd2-9bf3-f86aaee0c20a',
                code: 'Broken',
                name: 'Broken',
                displayOrder: 1
            },
            {
                id: '8c68791a-c69d-48c2-8ba7-ec76970f82cf',
                code: 'Knobs',
                name: 'Knobs',
                displayOrder: 2
            },
            {
                id: 'c3797bd2-ed6b-4aa5-81a9-36f52aab681a',
                code: 'Locks',
                name: 'Locks',
                displayOrder: 3
            },
            {
                id: '4e066fdc-d3b9-4386-b8cc-772b1c2dfc30',
                code: 'Brokenhinges',
                name: 'Broken hinges',
                displayOrder: 4
            },
            {
                id: '9544959d-c996-497e-be47-d233c0c59441',
                code: 'Slidingglassdoors',
                name: 'Sliding glass doors',
                displayOrder: 5
            },
            {
                id: '703a6cde-84d3-417e-bd49-4617581ca188',
                code: 'Ineffectivewaterproofing',
                name: 'Ineffective waterproofing',
                displayOrder: 6
            },
            {
                id: '8be3a2b0-7898-46e3-aa83-693cc75af2a3',
                code: 'Waterintrusionandorinsects',
                name: 'Water intrusion and/or insects',
                displayOrder: 7
            },
            {
                id: '8b228815-bb04-4470-9206-2aae2385afe3',
                code: 'Donotcloseproperly',
                name: 'Do not close properly',
                displayOrder: 8
            }
        ]
    },
    {
        id: '89d86666-955e-4248-8ba0-171c54238ad4',
        code: 'structure',
        name: 'Structural Issues',
        displayOrder: 13,
        options: [
            {
                id: 'b8431faf-a3c1-4124-865f-d4be9b5a1980',
                code: 'Bumpsinceiling',
                name: 'Bumps in ceiling',
                displayOrder: 1
            },
            {
                id: '557a1c97-f160-4c4a-8383-60025fd6215b',
                code: 'Holeinceiling',
                name: 'Hole in ceiling',
                displayOrder: 2
            },
            {
                id: '22632774-b39a-4400-9932-c461db593e26',
                code: 'Waterstainsonceiling',
                name: 'Water stains on ceiling',
                displayOrder: 3
            },
            {
                id: '3a100fce-ee03-4729-a661-772d837a1dfa',
                code: 'Waterstainsonwall',
                name: 'Water stains on wall',
                displayOrder: 4
            },
            {
                id: '76b3ba5b-953f-4e5a-9a72-85c4cd848f7c',
                code: 'Holeinwall',
                name: 'Hole in wall',
                displayOrder: 5
            },
            {
                id: '0e43eb88-4962-4f32-9bf5-14959405c9a5',
                code: 'Paint',
                name: 'Paint',
                displayOrder: 6
            },
            {
                id: '8d0007d8-b892-4d33-ac7d-d0d3ab106f34',
                code: 'Exteriordeckporch',
                name: 'Exterior deck/porch',
                displayOrder: 7
            },
            {
                id: '6abbd1db-4573-44cb-8594-240410a1ff72',
                code: 'Waterprooftoilet',
                name: 'Waterproof toilet',
                displayOrder: 8
            },
            {
                id: '094d045b-d13d-4951-9b8d-277fdd065aff',
                code: 'Waterprooftub',
                name: 'Waterproof tub',
                displayOrder: 9
            },
            {
                id: '4eb28396-622e-4aa7-996d-d88f696a17ac',
                code: 'Staircase',
                name: 'Staircase',
                displayOrder: 10
            },
            {
                id: 'e66e374e-a87e-442b-9675-1c69e5289656',
                code: 'Basementflood',
                name: 'Basement flood',
                displayOrder: 11
            },
            {
                id: '140a623f-2f14-48bd-ac86-93a58d1e1d43',
                code: 'Leaksingarage',
                name: 'Leaks in garage',
                displayOrder: 12
            },
            {
                id: 'aec548a8-8e29-4275-87d4-731a1eacc7c1',
                code: 'SoftSpotsduetoLeaks',
                name: 'Soft Spots due to Leaks',
                displayOrder: 13
            },
            {
                id: 'eb27c794-5274-4131-b1e1-18a6da97bf94',
                code: 'UneffectiveWaterproofingofthetubsortoilet',
                name: 'Ineffective Waterproofing of the Tubs or Toilet',
                displayOrder: 14
            },
            {
                id: '4a2cb569-226a-4347-a1ac-6fbb9ed5ddc0',
                code: 'IneffectiveWeatherproofingofanywindows',
                name: 'Ineffective Weatherproofing of Any Windows or Doors',
                displayOrder: 15
            }
        ]
    },
    {
        id: 'a3e4866d-2d1c-4000-9c0a-58866d6d8dc7',
        code: 'commonAreas',
        name: 'Common Area Problems',
        displayOrder: 14,
        options: [
            {
                id: 'b617db49-26ea-4214-bef6-5d5fa781c012',
                code: 'Mailboxbroken',
                name: 'Mailbox broken',
                displayOrder: 1
            },
            {
                id: '2686dec1-ca7c-404c-a300-b9cd88ec9ae9',
                code: 'Parkingareaissues',
                name: 'Parking area issues',
                displayOrder: 2
            },
            {
                id: 'aade5d17-9b79-4bba-83e9-af33209ed0c7',
                code: 'Damagetocars',
                name: 'Damage to cars',
                displayOrder: 3
            },
            {
                id: '091577bf-1451-4351-a5a1-8c556b7c1cf4',
                code: 'Flooding',
                name: 'Flooding',
                displayOrder: 4
            },
            {
                id: '279349e7-51f8-441a-b3b8-a20ab1751461',
                code: 'Entrancesblocked',
                name: 'Entrances blocked',
                displayOrder: 5
            },
            {
                id: '0de586bf-2bc0-41ee-806b-b39f9bd411dd',
                code: 'Swimmingpool',
                name: 'Swimming pool',
                displayOrder: 6
            },
            {
                id: '769a2802-f63e-4b2d-9cb6-23ae6ba42d32',
                code: 'Jacuzzi',
                name: 'Jacuzzi',
                displayOrder: 7
            },
            {
                id: 'adb22168-d58e-4ce3-af86-6f466ce52632',
                code: 'Laundryroom',
                name: 'Laundry room',
                displayOrder: 8
            },
            {
                id: '0809c292-6edb-483c-b8dd-ecc076a1e5fa',
                code: 'Recreationroom',
                name: 'Recreation room',
                displayOrder: 9
            },
            {
                id: 'dc5a7235-ddb4-41d3-8272-1aeb4a9922d2',
                code: 'Gym',
                name: 'Gym',
                displayOrder: 10
            },
            {
                id: '324e77e6-134e-4b19-81da-dfc2616cd1ea',
                code: 'Elevator',
                name: 'Elevator',
                displayOrder: 11
            },
            {
                id: 'c4edea6c-12c7-499d-ada0-b21f33c248f6',
                code: 'FilthRubbishGarbage',
                name: 'Filth/Rubbish/Garbage',
                displayOrder: 12
            },
            {
                id: '115c7e8f-1d3e-4df2-884e-bc6b68e2872f',
                code: 'Vermin',
                name: 'Vermin',
                displayOrder: 13
            },
            {
                id: '5a262e9b-3948-46f7-b581-14e4b020fc5a',
                code: 'Insects',
                name: 'Insects',
                displayOrder: 14
            },
            {
                id: '893a9a32-7a38-4fe9-bf35-db2a0ac349f6',
                code: 'BrokenGate',
                name: 'Broken gate',
                displayOrder: 15
            },
            {
                id: 'b0290bfd-2dc0-4784-8b91-1dd15b58a815',
                code: 'Blockedareasdoors',
                name: 'Blocked areas/doors',
                displayOrder: 16
            }
        ]
    },
    {
        id: '628925ca-a8c5-42b9-a44b-ba0eb55e3eff',
        code: 'trash',
        name: 'Trash Problems',
        displayOrder: 15,
        options: [
            {
                id: '66b4a722-d903-462f-a075-013ce8f1ad3b',
                code: 'Inadequatenumberofreceptacles',
                name: 'Inadequate number of receptacles',
                displayOrder: 1
            },
            {
                id: '94bf2d91-3c3f-42da-b90e-dd380d3037e4',
                code: 'Improperservicingemptying',
                name: 'Improper servicing/emptying',
                displayOrder: 2
            }
        ]
    },
    {
        id: 'ec467473-3e9c-45c3-a544-e0b58cb9ec01',
        code: 'nuisance',
        name: 'Nuisance Issues',
        displayOrder: 16,
        options: [
            {
                id: '37819267-24dc-4d1d-a978-337b7f7d800a',
                code: 'Drugs',
                name: 'Drugs',
                displayOrder: 1
            },
            {
                id: '78643721-a2b4-4f66-9f1f-e39fbda8b034',
                code: 'Smoking',
                name: 'Smoking',
                displayOrder: 2
            },
            {
                id: 'e0644ca9-b015-4940-89ab-9de81eee6548',
                code: 'Noisyneighbors',
                name: 'Noisy neighbors',
                displayOrder: 3
            },
            {
                id: '32720d5b-d29c-40aa-9ff7-6022406b0908',
                code: 'Gangs',
                name: 'Gangs',
                displayOrder: 4
            }
        ]
    },
    {
        id: 'd9add86b-5209-42dd-82a1-fd462bd0a88d',
        code: 'healthHazard',
        name: 'Health Hazards',
        displayOrder: 17,
        options: [
            {
                id: '38d820e9-c894-4842-acb4-7c2122e6f49a',
                code: 'Mold',
                name: 'Mold',
                displayOrder: 1
            },
            {
                id: '2beea61a-9fff-4c91-b91f-a8b650556c12',
                code: 'Mildew',
                name: 'Mildew',
                displayOrder: 2
            },
            {
                id: 'a6c1cab0-2987-47cc-9b3a-d2c8664a0b3c',
                code: 'Mushrooms',
                name: 'Mushrooms',
                displayOrder: 3
            },
            {
                id: '4f5788f9-ace4-490e-bbbf-3bb83b0f8873',
                code: 'Rawsewageonexterior',
                name: 'Raw sewage on exterior',
                displayOrder: 4
            },
            {
                id: '0d265711-b3ef-42cf-8ff5-20fe2cecf9cb',
                code: 'Noxiousfumes',
                name: 'Noxious fumes',
                displayOrder: 5
            },
            {
                id: '793cfece-3706-4c3f-8e6d-bafd4237ec9a',
                code: 'Chemicalpaintcontamination',
                name: 'Chemical/paint contamination',
                displayOrder: 6
            },
            {
                id: '92e7724d-87c6-4056-bf4b-1e2de696ba97',
                code: 'Toxicwaterpollution',
                name: 'Toxic water pollution',
                displayOrder: 7
            },
            {
                id: '9f73c845-ad4a-4b25-8908-766842125530',
                code: 'Offensiveodors',
                name: 'Offensive odors',
                displayOrder: 8
            }
        ]
    },
    {
        id: '9f3d41dd-575d-48d0-a1c9-1d183f47a09e',
        code: 'harassment',
        name: 'Harassment',
        displayOrder: 18,
        options: [
            {
                id: '23c5a60f-a241-49cd-aade-0c0bc4c6c926',
                code: 'UnlawfulDetainer',
                name: 'Unlawful detainer',
                displayOrder: 1
            },
            {
                id: '838d23e7-47df-4fbb-adfb-2c6cb55270c5',
                code: 'Evictionthreats',
                name: 'Eviction threats',
                displayOrder: 2
            },
            {
                id: '5bcbaa0c-138f-4d54-bc50-12dd7bf9d270',
                code: 'Bydefendant',
                name: 'By defendant',
                displayOrder: 3
            },
            {
                id: '69ed517c-f633-4948-8c01-486bf9156c13',
                code: 'Bymaintenancemanworkers',
                name: 'By maintenance man/workers',
                displayOrder: 4
            },
            {
                id: '0a46f6a1-e641-4ccc-87b5-b3cd04f803bf',
                code: 'Bymanagerbuildingstaff',
                name: 'By manager/building staff',
                displayOrder: 5
            },
            {
                id: '5893f418-e63d-48a1-a09f-3be232cef4b4',
                code: 'Byowner',
                name: 'By owner',
                displayOrder: 6
            },
            {
                id: '7ad6ea09-68b0-4c22-9941-a7e63bff3303',
                code: 'Othertenants',
                name: 'Other tenants',
                displayOrder: 7
            },
            {
                id: '691c6d94-a1b2-4827-9e25-2b725d6370e6',
                code: 'Illegitimatenotices',
                name: 'Illegitimate notices',
                displayOrder: 8
            },
            {
                id: '5d73f68a-d221-4547-8767-94b14649f128',
                code: 'Refusaltomaketimelyrepairs',
                name: 'Refusal to make timely repairs',
                displayOrder: 9
            },
            {
                id: '7cb61bd2-7a60-4013-839a-d62ce8c259f2',
                code: 'Writtenthreats',
                name: 'Written threats',
                displayOrder: 10
            },
            {
                id: 'd7865413-1a48-479d-a3b8-5978e14722e1',
                code: 'Aggressiveinappropriatelanguage',
                name: 'Aggressive/inappropriate language',
                displayOrder: 11
            },
            {
                id: '21bd8958-9ebd-4364-9f32-82a5012d3f06',
                code: 'Physicalthreatsortouching',
                name: 'Physical threats or touching',
                displayOrder: 12
            },
            {
                id: '501bc149-85d3-4d7b-a4f1-46ff3d8b32c3',
                code: 'Noticessinglingoutonetenantbutnotuniformlygiventoalltenants',
                name: 'Notices singling out one tenant but not uniformly given to all tenants',
                displayOrder: 13
            },
            {
                id: '9b5fb527-9556-4a69-9484-a7c858eacc79',
                code: 'Duplicativenotices',
                name: 'Duplicative notices',
                displayOrder: 14
            },
            {
                id: '950b8b17-d341-4212-b024-c04d64569bb2',
                code: 'UntimelyResponsefromLandlord',
                name: 'Untimely response from landlord',
                displayOrder: 15
            }
        ]
    },
    {
        id: '9a7d335a-c6fa-43d2-a166-b81b656f2873',
        code: 'notices',
        name: 'Notices Received',
        displayOrder: 19,
        options: [
            {
                id: 'd7635ad8-be8b-454c-95b4-0caec264a81b',
                code: '3day',
                name: '3-day',
                displayOrder: 1
            },
            {
                id: 'cd91d193-7f5c-4987-8aed-afdf6820c780',
                code: '24hour',
                name: '24-hour',
                displayOrder: 2
            },
            {
                id: '852743e5-d7cb-42ec-9739-4c05ae3e1484',
                code: '30day',
                name: '30-day',
                displayOrder: 3
            },
            {
                id: '7b0a9c51-1d2c-466b-930f-4daf62ebb18f',
                code: '60day',
                name: '60-day',
                displayOrder: 4
            },
            {
                id: '4c6e2d39-1c08-4ab8-a215-9ad6e9bff83d',
                code: 'Toquit',
                name: 'To quit',
                displayOrder: 5
            },
            {
                id: 'f92caecc-d511-4bfc-9170-556a874af8d7',
                code: 'Performorquit',
                name: 'Perform or quit',
                displayOrder: 6
            }
        ]
    },
    {
        id: '9e3cc4aa-5dff-4dcb-96a3-8328c21d523d',
        code: 'utility',
        name: 'Utility Interruptions',
        displayOrder: 20,
        options: [
            {
                id: '9d5a2344-e4c0-47cb-a168-a742272897d6',
                code: 'Gasleak',
                name: 'Gas leak',
                displayOrder: 1
            },
            {
                id: 'c8667ac2-0447-43be-b590-43595b625692',
                code: 'Watershutoffs',
                name: 'Water shutoffs',
                displayOrder: 2
            },
            {
                id: '5aa49efc-8dfd-4002-9905-957fad4551a2',
                code: 'Electricityshutoffs',
                name: 'Electricity shutoffs',
                displayOrder: 3
            },
            {
                id: '4386ff60-128c-4724-adff-82bbf8c080c6',
                code: 'Heatshutoff',
                name: 'Heat shutoff',
                displayOrder: 4
            },
            {
                id: '0bde1ab6-b648-48f9-9a3e-1d038714c3fd',
                code: 'Gasshutoff',
                name: 'Gas shutoff',
                displayOrder: 5
            }
        ]
    },
    {
        id: '3a5bb9cf-9968-46ea-86c8-ae16633e50b4',
        code: 'safety',
        name: 'Safety Issues',
        displayOrder: 21,
        options: [
            {
                id: '22249ec2-188b-4bfd-a4c4-8f2b79f24774',
                code: 'Brokeninoperablesecuritygate',
                name: 'Broken/inoperable security gate',
                displayOrder: 1
            },
            {
                id: '65d206bb-609d-4aed-94ba-ceec2fb589a5',
                code: 'Brokendoors',
                name: 'Broken doors',
                displayOrder: 2
            },
            {
                id: 'dbedb5b6-5cda-43bf-8eb4-e06f95fb9a50',
                code: 'Unauthorizedentries',
                name: 'Unauthorized entries',
                displayOrder: 3
            },
            {
                id: 'b035b5e2-69f6-44ee-bac5-e9982b220787',
                code: 'Brokenbuzzertogetin',
                name: 'Broken buzzer to get in',
                displayOrder: 4
            },
            {
                id: '430be662-7df0-492f-95bf-5bfb35531327',
                code: 'Securitycameras',
                name: 'Security cameras',
                displayOrder: 5
            },
            {
                id: '6a70b0f8-98e6-4eae-964a-12747873449f',
                code: 'Inoperablelocks',
                name: 'Inoperable locks',
                displayOrder: 6
            }
        ]
    },
    {
        id: 'b1a2a9ec-9e29-4209-8e5f-8608f7cb7986',
        code: 'injury',
        name: 'Injury Issues',
        displayOrder: 22,
        options: [
        ]
    },
    {
        id: '8318befd-81ec-4839-80f6-5dad9eb5b30c',
        code: 'nonresponsive',
        name: 'Nonresponsive Landlord',
        displayOrder: 23,
        options: [
        ]
    },
    {
        id: '3ba94b88-e504-473d-be34-e80ba1fd3891',
        code: 'unauthorized',
        name: 'Unauthorized Entries',
        displayOrder: 24,
        options: [
        ]
    },
    {
        id: '2b1c5ea8-2ce3-4633-b4fa-edb14c9b9c96',
        code: 'stolen',
        name: 'Stolen Items',
        displayOrder: 25,
        options: [
        ]
    },
    {
        id: '38df25ce-e982-4d5d-a6c0-6016b832159c',
        code: 'damaged',
        name: 'Damaged Items',
        displayOrder: 26,
        options: [
        ]
    },
    {
        id: '3a2531db-6e77-4219-88a5-40804ff07bb3',
        code: 'ageDiscrim',
        name: 'Age Discrimination',
        displayOrder: 27,
        options: [
        ]
    },
    {
        id: '008fe4b1-16bb-4a38-a67c-f41b2a775194',
        code: 'racialDiscrim',
        name: 'Racial Discrimination',
        displayOrder: 28,
        options: [
        ]
    },
    {
        id: '1c0b836a-dc16-4354-a7f4-01094501f5c4',
        code: 'disabilityDiscrim',
        name: 'Disability Discrimination',
        displayOrder: 29,
        options: [
        ]
    },
    {
        id: '52afcb56-63c6-4dd7-8f3e-a1ca20c8a1c5',
        code: 'securityDeposit',
        name: 'Security Deposit Issues',
        displayOrder: 30,
        options: [
        ]
    }
];

/**
 * Get category by code
 * @param code - Category code
 * @returns Category or undefined
 */
export function getCategoryByCode(code: string): IssueCategory | undefined {
    return ISSUE_CATEGORIES.find(cat => cat.code === code);
}

/**
 * Get option by code within a category
 * @param categoryCode - Category code
 * @param optionCode - Option code
 * @returns Option or undefined
 */
export function getOptionByCode(categoryCode: string, optionCode: string): IssueOption | undefined {
    const category = getCategoryByCode(categoryCode);
    return category?.options.find(opt => opt.code === optionCode);
}

/**
 * Get all option codes for a category
 * @param categoryCode - Category code
 * @returns Array of option codes
 */
export function getCategoryOptionCodes(categoryCode: string): string[] {
    const category = getCategoryByCode(categoryCode);
    return category?.options.map(opt => opt.code) || [];
}

/**
 * Validate if a category code exists
 * @param code - Category code to validate
 * @returns true if valid
 */
export function isValidCategoryCode(code: string): boolean {
    return ISSUE_CATEGORIES.some(cat => cat.code === code);
}

/**
 * Validate if an option code exists for a category
 * @param categoryCode - Category code
 * @param optionCode - Option code
 * @returns true if valid
 */
export function isValidOptionCode(categoryCode: string, optionCode: string): boolean {
    return getOptionByCode(categoryCode, optionCode) !== undefined;
}

/**
 * Get all valid category codes
 * @returns Array of all category codes
 */
export function getAllCategoryCodes(): string[] {
    return ISSUE_CATEGORIES.map(cat => cat.code);
}
