# Cloud Build Configuration - STAGING
# Triggers on push to any branch EXCEPT 'main'
# Auto-deploys without manual approval
#
# Features:
# - Same testing as production
# - Faster deployment (no gradual rollout)
# - Deploys to node-server-staging service
# - Uses staging database

steps:
  # ============================================
  # STEP 1: Install Dependencies
  # ============================================
  - name: 'node:20'
    id: 'install'
    entrypoint: npm
    args: ['ci']
    env:
      - 'NODE_ENV=staging'
      - 'CI=true'

  # ============================================
  # STEP 2: Run Linting
  # ============================================
  - name: 'node:20'
    id: 'lint'
    entrypoint: npm
    args: ['run', 'lint']
    waitFor: ['install']

  # ============================================
  # STEP 3: Run Unit Tests
  # ============================================
  - name: 'node:20'
    id: 'test-unit'
    entrypoint: npm
    args: ['run', 'test:unit']
    env:
      - 'NODE_ENV=test'
    waitFor: ['install']

  # ============================================
  # STEP 4: Run Integration Tests
  # ============================================
  - name: 'node:20'
    id: 'test-integration'
    entrypoint: npm
    args: ['run', 'test:integration']
    env:
      - 'NODE_ENV=test'
      - 'DB_NAME=staging_legal_forms'
      - 'DB_USER=postgres'
      - 'INSTANCE_CONNECTION_NAME=${_STAGING_INSTANCE_CONNECTION_NAME}'
    secretEnv: ['STAGING_DB_PASSWORD']
    waitFor: ['install']

  # ============================================
  # STEP 5: Build Docker Image
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/node-server-staging:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/node-server-staging:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/node-server-staging:staging-$BUILD_ID'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/node-server-staging:latest'
      - '--build-arg'
      - 'NODE_ENV=staging'
      - '.'
    waitFor: ['lint', 'test-unit', 'test-integration']

  # ============================================
  # STEP 6: Push Images
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-commit'
    args: ['push', 'gcr.io/$PROJECT_ID/node-server-staging:$COMMIT_SHA']
    waitFor: ['build']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args: ['push', 'gcr.io/$PROJECT_ID/node-server-staging:latest']
    waitFor: ['build']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-tagged'
    args: ['push', 'gcr.io/$PROJECT_ID/node-server-staging:staging-$BUILD_ID']
    waitFor: ['build']

  # ============================================
  # STEP 7: Deploy to Staging (100% Traffic)
  # ============================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-staging'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'node-server-staging'
      - '--image=gcr.io/$PROJECT_ID/node-server-staging:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--min-instances=0'  # Can scale to zero on staging
      - '--max-instances=5'   # Lower max for cost savings
      - '--concurrency=80'
      - '--cpu=1'             # Less CPU than production
      - '--memory=1Gi'        # Less memory than production
      - '--timeout=60s'
      - '--cpu-throttling'
      - '--execution-environment=gen2'
      - '--set-env-vars=NODE_ENV=staging,BUILD_ID=$BUILD_ID,INSTANCE_CONNECTION_NAME=${_STAGING_INSTANCE_CONNECTION_NAME}'
      - '--set-secrets=ACCESS_TOKEN=access-token-staging:latest,SENDGRID_API_KEY=sendgrid-api-key-staging:latest,DB_PASSWORD=db-password-staging:latest,RECAPTCHA_SECRET_KEY=recaptcha-secret-key-staging:latest'
      - '--set-cloudsql-instances=${_STAGING_INSTANCE_CONNECTION_NAME}'
      - '--service-account=${_SERVICE_ACCOUNT}'
      - '--allow-unauthenticated'
    waitFor: ['push-commit']

  # ============================================
  # STEP 8: Smoke Tests
  # ============================================
  - name: 'gcr.io/cloud-builders/curl'
    id: 'smoke-test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_URL=$(gcloud run services describe node-server-staging \
          --region=${_REGION} \
          --format="value(status.url)")
        
        echo "Staging URL: $SERVICE_URL"
        
        # Wait for service to be ready
        echo "Waiting 10s for service to start..."
        sleep 10
        
        # Test health
        echo "Testing /health..."
        curl -f -s "$SERVICE_URL/health" || exit 1
        
        # Test readiness
        echo "Testing /health/ready..."
        curl -f -s "$SERVICE_URL/health/ready" || exit 1
        
        # Test detailed health
        echo "Testing /health/detailed..."
        curl -f -s "$SERVICE_URL/health/detailed" | jq . || exit 1
        
        echo "✅ All smoke tests passed"
        echo "Staging deployed at: $SERVICE_URL"
    waitFor: ['deploy-staging']

  # ============================================
  # STEP 9: Clean Up Old Staging Revisions
  # ============================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'cleanup'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🧹 Cleaning up old staging revisions (keeping last 3)..."
        
        OLD_REVISIONS=$(gcloud run revisions list \
          --service=node-server-staging \
          --region=${_REGION} \
          --format="value(metadata.name)" \
          --sort-by="~metadata.creationTimestamp" \
          | tail -n +4)
        
        for revision in $OLD_REVISIONS; do
          echo "Deleting old revision: $revision"
          gcloud run revisions delete $revision \
            --region=${_REGION} \
            --quiet || true
        done
        
        echo "✅ Cleanup complete"
    waitFor: ['smoke-test']

# ============================================
# Secrets from Secret Manager
# ============================================
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/db-password-staging/versions/latest
      env: 'STAGING_DB_PASSWORD'

# ============================================
# Substitution Variables
# ============================================
substitutions:
  _REGION: 'us-central1'
  _STAGING_INSTANCE_CONNECTION_NAME: 'docmosis-tornado:us-central1:legal-forms-db-staging'
  _SERVICE_ACCOUNT: '${PROJECT_NUMBER}-compute@developer.gserviceaccount.com'

# ============================================
# Build Options
# ============================================
timeout: 1200s  # 20 minutes max

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'
  diskSizeGb: 100

# ============================================
# Images
# ============================================
images:
  - 'gcr.io/$PROJECT_ID/node-server-staging:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/node-server-staging:latest'
  - 'gcr.io/$PROJECT_ID/node-server-staging:staging-$BUILD_ID'