-- ============================================================================
-- Migration 010: CRM Dashboard Tables
-- ============================================================================
-- Date: 2025-12-11
-- Phase: 7A.1 - Database Foundation for CRM Dashboard
--
-- Additive migration - no modifications to existing tables
-- Creates: generated_documents, case_dashboard, case_activities, case_notes
--
-- NOTE: This migration uses client_intakes (not intakes) as the intake table name
-- and uses UUID types for all foreign keys to match existing schema conventions.
--
-- NOTE: The existing `attorneys` table is used for assignments. NULL assigned_attorney_id
-- means "unassigned". The attorneys table already exists as an auth table with columns:
-- id, email, password_hash, full_name, role, active, created_at, last_login
--
-- PRIMARY KEY TYPE NOTE: This migration uses SERIAL PRIMARY KEY for new tables
-- (case_dashboard, case_activities, case_notes, generated_documents) while existing
-- schema tables (client_intakes, cases) use UUID PRIMARY KEY. This is intentional:
-- - UUID: Better for distributed systems, external references, and intake form IDs
-- - SERIAL: Simpler for internal CRM workflow tables with high insert frequency
-- The two approaches coexist without issues since tables are linked by UUID foreign keys.
-- ============================================================================

BEGIN;

-- ============================================================================
-- 1. Generated Documents Table
-- ============================================================================
-- Tracks documents created from doc gen form
-- Links to both intake (source) and case (doc gen record) where applicable
-- Note: case_id FK is commented out because cases table may not exist yet
-- Uncomment the REFERENCES clause when cases table is created
CREATE TABLE IF NOT EXISTS generated_documents (
    id SERIAL PRIMARY KEY,
    intake_id UUID REFERENCES client_intakes(id) ON DELETE SET NULL,
    case_id UUID, -- Will reference cases(id) when that table exists

    -- Document identification
    document_type VARCHAR(100) NOT NULL,  -- 'complaint', 'demand_letter', 'srogs', 'pods', 'admissions', etc.
    document_name VARCHAR(255) NOT NULL,

    -- Storage paths
    file_path TEXT,                        -- Local or cloud storage path
    dropbox_path TEXT,                     -- Dropbox path if uploaded
    file_size_bytes INTEGER,

    -- Generation metadata
    generated_by VARCHAR(255),             -- User who generated
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Status tracking
    status VARCHAR(50) DEFAULT 'generated' CHECK (status IN (
        'generated', 'uploaded', 'sent', 'filed', 'error'
    )),

    -- Timestamps
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Flexible metadata storage
    metadata JSONB DEFAULT '{}'::jsonb
);

COMMENT ON TABLE generated_documents IS 'Tracks documents generated by the doc gen system, linked to intakes and/or cases';

CREATE INDEX IF NOT EXISTS idx_generated_documents_intake ON generated_documents(intake_id);
CREATE INDEX IF NOT EXISTS idx_generated_documents_case ON generated_documents(case_id);
CREATE INDEX IF NOT EXISTS idx_generated_documents_status ON generated_documents(status);
CREATE INDEX IF NOT EXISTS idx_generated_documents_type ON generated_documents(document_type);
CREATE INDEX IF NOT EXISTS idx_generated_documents_generated_at ON generated_documents(generated_at DESC);

-- ============================================================================
-- 3. Case Dashboard Table
-- ============================================================================
-- Workflow metadata layer for CRM functionality
-- Does not duplicate case data - references client_intakes and optionally cases
CREATE TABLE IF NOT EXISTS case_dashboard (
    id SERIAL PRIMARY KEY,

    -- Reference to intake (required) and case (optional, set when loaded into doc gen)
    intake_id UUID UNIQUE NOT NULL REFERENCES client_intakes(id) ON DELETE CASCADE,
    case_id UUID, -- Will reference cases(id) when that table exists

    -- Workflow status
    status VARCHAR(50) DEFAULT 'new' CHECK (status IN (
        'new', 'in_review', 'docs_in_progress', 'docs_generated',
        'sent_to_client', 'filed', 'closed', 'on_hold'
    )),
    status_changed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    status_changed_by VARCHAR(255),

    -- Assignment (NULL = unassigned, references existing attorneys auth table)
    assigned_attorney_id INTEGER REFERENCES attorneys(id) ON DELETE SET NULL,
    assigned_at TIMESTAMP WITH TIME ZONE,
    assigned_by VARCHAR(255),

    -- Flags
    is_priority BOOLEAN DEFAULT false,
    is_archived BOOLEAN DEFAULT false,

    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Document generation tracking
    docs_generated_at TIMESTAMP WITH TIME ZONE,
    docs_generated_by VARCHAR(255),
    last_doc_gen_count INTEGER DEFAULT 0
);

COMMENT ON TABLE case_dashboard IS 'CRM dashboard workflow layer linking to client_intakes. Tracks status, assignments, and activity.';

CREATE INDEX IF NOT EXISTS idx_case_dashboard_status ON case_dashboard(status);
CREATE INDEX IF NOT EXISTS idx_case_dashboard_attorney ON case_dashboard(assigned_attorney_id);
CREATE INDEX IF NOT EXISTS idx_case_dashboard_priority ON case_dashboard(is_priority) WHERE is_priority = true;
CREATE INDEX IF NOT EXISTS idx_case_dashboard_intake ON case_dashboard(intake_id);
CREATE INDEX IF NOT EXISTS idx_case_dashboard_case ON case_dashboard(case_id);
CREATE INDEX IF NOT EXISTS idx_case_dashboard_archived ON case_dashboard(is_archived) WHERE is_archived = false;

-- ============================================================================
-- 4. Case Activities Table (Timeline/Audit Log)
-- ============================================================================
CREATE TABLE IF NOT EXISTS case_activities (
    id SERIAL PRIMARY KEY,
    dashboard_id INTEGER NOT NULL REFERENCES case_dashboard(id) ON DELETE CASCADE,
    intake_id UUID REFERENCES client_intakes(id) ON DELETE SET NULL,

    -- Activity details
    activity_type VARCHAR(50) NOT NULL CHECK (activity_type IN (
        'created', 'status_changed', 'assigned', 'note_added', 'note_edited',
        'doc_generated', 'doc_uploaded', 'priority_changed', 'archived', 'unarchived',
        'loaded_to_docgen', 'case_linked'
    )),
    description TEXT NOT NULL,

    -- Actor
    performed_by VARCHAR(255),
    performed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Change tracking (for status changes)
    old_value VARCHAR(255),
    new_value VARCHAR(255),

    -- Flexible metadata
    metadata JSONB DEFAULT '{}'::jsonb
);

COMMENT ON TABLE case_activities IS 'Audit log and activity timeline for dashboard cases';

CREATE INDEX IF NOT EXISTS idx_case_activities_dashboard ON case_activities(dashboard_id);
CREATE INDEX IF NOT EXISTS idx_case_activities_intake ON case_activities(intake_id);
CREATE INDEX IF NOT EXISTS idx_case_activities_type ON case_activities(activity_type);
CREATE INDEX IF NOT EXISTS idx_case_activities_date ON case_activities(performed_at DESC);

-- ============================================================================
-- 5. Case Notes Table
-- ============================================================================
CREATE TABLE IF NOT EXISTS case_notes (
    id SERIAL PRIMARY KEY,
    dashboard_id INTEGER NOT NULL REFERENCES case_dashboard(id) ON DELETE CASCADE,
    intake_id UUID REFERENCES client_intakes(id) ON DELETE SET NULL,

    -- Note content
    content TEXT NOT NULL,
    is_pinned BOOLEAN DEFAULT false,

    -- Authorship
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Soft delete
    is_deleted BOOLEAN DEFAULT false,
    deleted_at TIMESTAMP WITH TIME ZONE,
    deleted_by VARCHAR(255)
);

COMMENT ON TABLE case_notes IS 'Internal notes for dashboard cases with soft delete support';

CREATE INDEX IF NOT EXISTS idx_case_notes_dashboard ON case_notes(dashboard_id);
CREATE INDEX IF NOT EXISTS idx_case_notes_intake ON case_notes(intake_id);
CREATE INDEX IF NOT EXISTS idx_case_notes_pinned ON case_notes(is_pinned) WHERE is_pinned = true AND is_deleted = false;
CREATE INDEX IF NOT EXISTS idx_case_notes_active ON case_notes(dashboard_id) WHERE is_deleted = false;

-- ============================================================================
-- 6. Trigger: Auto-update updated_at
-- ============================================================================
CREATE OR REPLACE FUNCTION update_dashboard_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION update_dashboard_timestamp() IS 'Auto-updates updated_at timestamp on row modification';

-- Apply triggers
CREATE TRIGGER trigger_case_dashboard_updated
    BEFORE UPDATE ON case_dashboard
    FOR EACH ROW
    EXECUTE FUNCTION update_dashboard_timestamp();

CREATE TRIGGER trigger_case_notes_updated
    BEFORE UPDATE ON case_notes
    FOR EACH ROW
    EXECUTE FUNCTION update_dashboard_timestamp();

CREATE TRIGGER trigger_generated_documents_updated
    BEFORE UPDATE ON generated_documents
    FOR EACH ROW
    EXECUTE FUNCTION update_dashboard_timestamp();

-- Note: attorneys table already exists with its own update logic

-- ============================================================================
-- 7. Trigger: Auto-update status_changed_at on status change
-- ============================================================================
CREATE OR REPLACE FUNCTION update_status_changed_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.status IS DISTINCT FROM NEW.status THEN
        NEW.status_changed_at = CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION update_status_changed_timestamp() IS 'Auto-updates status_changed_at when status field changes';

CREATE TRIGGER trigger_case_dashboard_status_changed
    BEFORE UPDATE ON case_dashboard
    FOR EACH ROW
    EXECUTE FUNCTION update_status_changed_timestamp();

-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================
-- Tables created:
-- 1. generated_documents
-- 2. case_dashboard (references existing attorneys table)
-- 3. case_activities
-- 4. case_notes
--
-- Triggers created:
-- - trigger_case_dashboard_updated
-- - trigger_case_notes_updated
-- - trigger_case_dashboard_status_changed
--
-- Note: Uses existing attorneys table for assignments (NULL = unassigned)
-- ============================================================================

COMMIT;
