# Grafana Datasource Configuration
#
# Automatically provisions Prometheus as a datasource when Grafana starts.
# No manual configuration needed!

apiVersion: 1

# List of datasources to insert/update
datasources:
  # Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
